<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->getTitle();?></title>
<meta name="author" content="DDM" />
<link href="<?php echo Ddm_Controller::singleton()->getCurrentBaseUrl();?>design/install/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="top-line"></div>
<div class="container">
	<div class="logo">
		<div class="logo-left"><img src="<?php echo Ddm_Controller::singleton()->getCurrentBaseUrl();?>modules/Core/design/frontend/default/images/logo.jpg" alt="DDMCMS" /></div>
		<div class="logo-left">&nbsp;</div>
	</div>
</div>
<div class="container">
