<form method="get" action="./index.php">
	<input type="hidden" name="step" value="check" />
	<div class="main-body">
		<div class="install-ui">
			<h1>欢迎使用DDMCMS</h1>
			<div class="license">
				<p>© 2014-2015 DDMCMS 保留所有权利。</p>
				<p>感谢您选择 DDMCMS系统。希望我们的努力能为您提供一个高效快速和强大的个人或企业网站解决方案。</p>
				<p>无论个人或组织、盈利与否、用途如何（包括以学习和研究为目的），均只能在不用于商业目的的前提下对程序代码进行修改和使用，不允许对程序代码以任何形式任何目的的再发布。</p>
			</div>
			<div class="buttons"><button type="submit">我知道了, 继续下一步</button></div>
		</div>
	</div>
</form>