<?php /* @var $this Core_Block_head */?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->getTemplateObject()->title;?></title>
<?php echo $this->getTemplateObject()->getMeta(true);?>
<?php echo $this->getTemplateObject()->getCss(true);?>
<?php echo $this->getTemplateObject()->getJs(true);?>
<?php if($this->getTemplateObject()->getJavascript()){?>
<script type="text/javascript">
<!--
<?php echo $this->getTemplateObject()->getJavascript(),"\r\n";?>
//-->
</script>
<?php }
if($this->getTemplateObject()->getStyle()){?>
<style type="text/css"><?php echo "\r\n",$this->getTemplateObject()->getStyle(),"\r\n";?></style>
<?php }?>